gradle/native-platform

build.gradle

In most cases it should not make a difference (having both ncurses 6 and legacy 5 installed), however version 6 is newer and in a long run has a chance to contain some bug fixes and enhancements not available in version 5.

Prefer ncurses 6 over 5

---

build.gradle
src/main/cpp/apple.cpp
src/main/java/net/rubygrapefruit/platform/Memory.java
src/main/java/net/rubygrapefruit/platform/MemoryInfo.java
src/main/java/net/rubygrapefruit/platform/OsxMemory.java
src/main/java/net/rubygrapefruit/platform/OsxMemoryInfo.java
src/main/java/net/rubygrapefruit/platform/internal/DefaultMemory.java
src/main/java/net/rubygrapefruit/platform/internal/DefaultMemoryInfo.java
src/main/java/net/rubygrapefruit/platform/internal/DefaultOsxMemory.java
src/main/java/net/rubygrapefruit/platform/internal/DefaultOsxMemoryInfo.java
src/main/java/net/rubygrapefruit/platform/internal/Platform.java
src/main/java/net/rubygrapefruit/platform/internal/jni/MemoryFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/OsxMemoryFunctions.java
src/test/groovy/net/rubygrapefruit/platform/MemoryTest.groovy
src/test/groovy/net/rubygrapefruit/platform/OsxMemoryTest.groovy

Uses `sysctl` to query total physical memory.
Uses `host_statistics64` to calculate available physical memory (`free_count + inactive_count - speculative_count`).
Do not rely on `external_page_count` which should be the file cache because it is available since OSX 10.9 only and it shown inaccurate (larger than total memory) values with long uptime or under load.
Subtract `speculative` in order to provide a pessimistic result rather than an optimistic one.

MemoryInfo implementation for MAC

---

build.gradle
src/main/cpp/freebsd_kevents.cpp
src/main/cpp/posix.cpp
src/test/groovy/net/rubygrapefruit/platform/file/AbstractFilesTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/FilesTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/PosixFilesTest.groovy

There are a couple of things in this pull request:
- Changes so that `stat()` does not return an exception when something in the path happens to match some existing file.  It now treats it like the path is not found rather than an error.
- Changes to build with Xcode10 on OSX.  This also drops support for OSX 32-bit.
- Some updates/refactors to tests to get them to pass on various platforms:
- Ignore the test for file names longer than the 260 character max on windows.
- Resolve the timestamp difference between `stat()` and java file methods on macOS.
- Fix an issue on OSX/jdk8 where closing the file watch was causing an EBADF instead of EINTR when polling for the next change.
The tests all pass for me now on both jdk7 and jdk8 on OSX, Linux and Windows.  I did not find any jvm-specific …

Allow stat() to handle paths that happen to match an existing file 

---

src/test/groovy/net/rubygrapefruit/platform/file/AbstractFilesTest.groovy

Fixes difference between oracle jdk 8 and openjdk 8.

Always round timestamps on linux/OSX

---

src/main/cpp/posix.cpp
src/shared/cpp/generic_posix.cpp
src/shared/cpp/osx.cpp
src/shared/headers/generic.h
src/test/groovy/net/rubygrapefruit/platform/ProcessTest.groovy

This mitigates the issue by always using utf-8 encoding when getting/setting environment variables.  I feel like this is the simplest solution to the problem.  Other places where we convert, we continue to use the C-locale-dependent conversion methods, but for environment variables, we always use utf-8.
The issue with converting to bytes on the Java side and passing a byte array in is that on Windows, we don't set the environment variable using `char *`, we need `wchar *`, so if we pass in bytes then we have the opposite problem and we have to do the same conversion on windows now and potentially open ourselves to the same problem.
I also looked into doing a C-locale-dependent conversion first, and then trying the Java-byte-conversion method, but I found scenarios where this would fail. …

Resolve issues with supplementary characters being set in environment variables

---

src/main/cpp/win.cpp
src/test/groovy/net/rubygrapefruit/platform/file/FilesTest.groovy
test-app/src/main/java/net/rubygrapefruit/platform/test/Main.java

* For local paths, we use the `\\?\` prefix
* For UNC paths, we use the `\\?\UNC\` prefix
* Added a `--long-paths` option to the test app to verify behavior

Windows: Add support for paths longer than 260 characters

---

build.gradle
src/main/java/net/rubygrapefruit/platform/SystemInfo.java
src/main/java/net/rubygrapefruit/platform/internal/MutableSystemInfo.java
src/main/java/net/rubygrapefruit/platform/internal/Platform.java

In addition to the new platform definitions, additional targets need to be explicitly added to the GCC toolchain because the core Gradle GCC toolchain only supports x86 and x86_64 out of the box.

Support for aarch64 on linux.

---

src/main/cpp/win.cpp
src/main/java/net/rubygrapefruit/platform/file/WindowsFiles.java
src/main/java/net/rubygrapefruit/platform/internal/DefaultWindowsFiles.java
src/main/java/net/rubygrapefruit/platform/internal/jni/WindowsFileFunctions.java
src/test/groovy/net/rubygrapefruit/platform/file/AbstractFilesTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/FilesTest.groovy
test-app/src/main/java/net/rubygrapefruit/platform/test/Main.java

Windows: Add support for SYMLINKS
* Both `stat` and `readdir` entry points support returning FILE_TYPE_SYMLINK
* Both `stat` and `readdir` entry points support the "followLink" parameter
* Add a `stat-L` option in the test app (`stat` with `followLink` option)
* Add a `ls-L` option in test app (`ls` with `followLink` option)
* Requires Windows Vista/Windows Server 2008 or later

Windows: Add support for SYMLINKS

---

src/main/cpp/posix.cpp
src/main/cpp/win.cpp
src/main/java/net/rubygrapefruit/platform/SystemInfo.java
src/main/java/net/rubygrapefruit/platform/internal/DefaultSystemInfo.java
src/main/java/net/rubygrapefruit/platform/internal/MutableSystemInfo.java
src/test/groovy/net/rubygrapefruit/platform/SystemInfoTest.groovy
test-app/src/main/java/net/rubygrapefruit/platform/test/Main.java

Currently for posix systems this uses the nodename returned by uname rather than the hostname call as a) we are already calling uname and b) on MacOS and Linux these apparently return the same thing anyway.
Windows implementation will probably use GetComputerName, yet to be implemented.

Add system hostname

---

.gitignore
build.gradle
buildSrc/src/main/java/BasePublishPlugin.java
buildSrc/src/main/java/PublishSnapshotPlugin.java
buildSrc/src/main/java/ReleasePlugin.java
buildSrc/src/main/java/UploadPlugin.java
buildSrc/src/main/java/UploadTask.java
buildSrc/src/main/java/VersionDetails.java

This PR allows publishing snapshots, which use a timestamped version number. Moreover, it is possible to publish snapshots with fewer supported OSes to the Gradle snapshot repository.

Allow publishing partial snapshot variant

---

src/main/cpp/apple_fsnotifier.cpp
src/main/java/net/rubygrapefruit/platform/internal/jni/NativeLibraryFunctions.java
src/shared/headers/generic.h

When Gradle locks a file, the macOS watchers receive a `0x10400`event. That is `kFSEventStreamEventFlagItemInodeMetaMod | kFSEventStreamEventFlagItemIsFile `.
This currently causes Gradle to drop the whole VFS state when used on the `gradle/gradle` build.
This PR hands on the change as `MODIFIED` to the Java side. Another option would be to completely ignore the event.

Handle locking file event on macOS

---

src/main/cpp/apple_fsnotifier.cpp
src/main/cpp/win_fsnotifier.cpp

Instead of trying to attach the thread to the JVM every time we report a change, we only attach it when the thread starts and detach it at the end so the JVM can exit.
Fixes https://github.com/adammurdoch/native-platform/issues/56.

Better JNI thread management

---

src/main/cpp/apple_fsnotifier.cpp
src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventsTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/WindowsFileEventFunctionsTest.groovy

We didn't handle the event when a watched directory was deleted in its entirety. Now we do.

macOS handle watched directory hierarchy deleted event

---

build.gradle

So a working version can be published to the local Maven repository
and used from another build.

Allow depending only on the variants which can be built locally

---

build.gradle

Now that there are FreeBSD agents, we also can publish the variant from CI.

Publish FreeBSD variant from CI

---

src/main/cpp/apple_fsnotifier.cpp
src/main/cpp/win_fsnotifier.cpp
src/shared/cpp/generic.cpp
src/shared/cpp/generic_posix.cpp
src/shared/cpp/win.cpp

Since the logging may be called from a native thread,
the String needs to be freed. If not, the log messages
will not be garbage collected.
This fixes a memory leak exposed by the soak test in `gradle/gradle`: https://github.com/gradle/gradle/pull/12253

Free strings used to call back to Java from native threads

---

src/main/cpp/apple_fsnotifier.cpp

Doing so produces this log:
```text
2020-02-17 23:02 java[50430] (FSEvents.framework) FSEventStreamFlushSync(): failed assertion '(SInt64)last_id > 0LL'
```
The recommendation seems to be not to call `FSEventStreamFlushSync()` at all. See https://github.com/nodejs/node/issues/854#issuecomment-294892950.

Do not flush FSEventStream

---

.teamcity/NativePlatformPublishing.kt
build.gradle
readme.md

So all variants can be built on CI.
Given that most Linux OSes are dropping 32bit support, it seems safe to remove the 32bit support. Same goes for stdlib support for FreeBSD, given that the GCC toolchain was deprecated in FreeBSD 10
Replaces #65.

Remove support for 32bit and stdcpp

---

src/file-events/cpp/apple_fsnotifier.cpp
src/file-events/cpp/win_fsnotifier.cpp
src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/OsxFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/WindowsFileEventFunctions.java

We are now throwing exceptions from the native side now.

Do not pass `FunctionResult` objects to JNI calls

---

src/file-events/cpp/apple_fsnotifier.cpp
src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/win_fsnotifier.cpp
src/file-events/headers/apple_fsnotifier.h
src/file-events/headers/generic_fsnotifier.h
src/file-events/headers/win_fsnotifier.h
src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventsTest.groovy

This is to make it work more similarly to the Windows watcher. Doing this will make it easier to start and stop watching things dynamically.

Register each watched path individually on macOS

---

src/file-events/cpp/win_fsnotifier.cpp
src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventsTest.groovy

It is unclear when we should receive an event with an empty file name (maybe when the watched directory itself is changed?), and why these things started to cause `StringIndexOutOfBoundsException` (or whether they are the culprit). However, this case needs to be handled, so here's a fix.
I'm also strengthening our tests by checking if the reported change is an absolute path and failing the test if it isn't.

Handle empty file name received in event notification on Windows

---

src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/headers/generic_fsnotifier.h
src/file-events/headers/linux_fsnotifier.h
src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventsTest.groovy

Fixes a problem when we stop and start watching the same directory in quick succession on Linux.

Wait for cancelled watch point to be finished on Linux

---

src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/cpp/win_fsnotifier.cpp

Asserts crash the VM with a message we cannot track on the Java side. Instead, we'll let things proceed, and let the VM crash with `SIGSEGV`, which forces the JVM to produce a crash log. Which is a lot nicer.

Remove `assert()` calls for `NULL` checks

---

src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/headers/generic_fsnotifier.h

so all threads can access it and don't fall back to
the system classloader.

Load exception class via JNI_OnLoad

---

src/file-events/cpp/apple_fsnotifier.cpp
src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/jni_support.cpp
src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/cpp/logging.cpp
src/file-events/cpp/services.cpp
src/file-events/cpp/win_fsnotifier.cpp
src/file-events/headers/apple_fsnotifier.h
src/file-events/headers/generic_fsnotifier.h
src/file-events/headers/jni_support.h
src/file-events/headers/linux_fsnotifier.h
src/file-events/headers/logging.h
src/file-events/headers/win_fsnotifier.h
src/main/java/net/rubygrapefruit/platform/internal/Platform.java
src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/NativeLogger.java
src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventFunctionsTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
src/test/groovy/net/rubygrapefruit/platform/testfixture/JulLogging.java

A number of improvements around logging:
- no initialization of the logging required, instead we initialize in `JNI_OnLoad()`
- log level is queried from the native side, and cached for 1 second
- no need to pass `JNIEnv*` to logging anymore
- `log_fine()` etc. is replaced with `log(FINE, ...)`
- added `jni_support.cpp` with all the JNI stuff
- assed `JniSupport` for types that need to work with JNI
- added `JniGlobalRef` RAII

Logging, take 2

---

.teamcity/NativePlatformBuild.kt

Sometimes Teamcity seems to hang on the builds. Let's see
if increasing the build timeout helps.

Increase build timeout to 15 minutes

---

src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/headers/linux_fsnotifier.h

A timeout doesn't seem to be necessary.

Do not block on unregistering a watch point on Linux

---

src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/headers/generic_fsnotifier.h

We shouldn't wait forever for the background thread to start or for commands to execute.

Wait only five seconds for thread operations

---

src/file-events/cpp/apple_fsnotifier.cpp
src/file-events/cpp/file-events-version.cpp
src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/cpp/win_fsnotifier.cpp
src/file-events/headers/generic_fsnotifier.h
src/main/java/net/rubygrapefruit/platform/file/FileWatcher.java
src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/LinuxFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/OsxFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/WindowsFileEventFunctions.java
src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventFunctionsTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy
test-app/src/main/java/net/rubygrapefruit/platform/test/Main.java

On Windows and macOS typically we only want to watch a small number of paths that don't change over time, as each path is watched recursively. However, on Linux watch points need to be (un)registered frequently and en masse. The current API requires each change to be communicated to the server in a separately synchronized `Command` which is slow. Instead we want to allow the application to pass a number of watch points in at the same time.

Allow (un)registering multiple paths at once

---

src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy

This is similar to the test on Linux, only for the hierarchical
watchers.

Add a test for hierarchical watchers deleting a hierarchy

---

src/file-events/cpp/apple_fsnotifier.cpp
src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/cpp/win_fsnotifier.cpp
src/file-events/headers/apple_fsnotifier.h
src/file-events/headers/generic_fsnotifier.h
src/file-events/headers/linux_fsnotifier.h
src/file-events/headers/win_fsnotifier.h
src/main/java/net/rubygrapefruit/platform/file/FileWatcher.java
src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventFunctionsTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy

The macOS native watcher emits `Path not watched:` messages upon shutdown. This is caused by incorrectly allocating a `std::vector`. This PR fixes the allocation and reverts another attempted (but not working) workaround targeted at the same problem.

Fix closing empty watchpoint on macOS

---

build.gradle
src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/jni_support.cpp
src/file-events/cpp/logging.cpp
src/file-events/cpp/services.cpp
src/file-events/headers/generic_fsnotifier.h
src/file-events/headers/jni_support.h
src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventFunctionsTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy
src/test/groovy/net/rubygrapefruit/platform/testfixture/JniChecksEnabled.java

Add a separate test task that runs with `-Xcheck:jni` for file-events stuff. We should probably enable `pedantic`, see https://www.ibm.com/support/knowledgecenter/SSB23S_1.1.0.2019/com.ibm.java.vm.80.doc/docs/jni_debug.html

Run tests with JNI checks enabled

---

src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy

Closing the watcher causes the destructor
of the server to throw an exception when the
terminate command runs into timeout.

Add test for crash when closing the server while the event queue is blocked

---

src/file-events/cpp/jni_support.cpp
src/file-events/cpp/linux_fsnotifier.cpp
src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy

Exceptions from the Java side with no message
caused the native code to crash.

Fix crash when catching exception from callback

---

src/file-events/cpp/win_fsnotifier.cpp
src/file-events/headers/win_fsnotifier.h
src/main/java/net/rubygrapefruit/platform/internal/jni/WindowsFileEventFunctions.java
src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventFunctionsTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy
test-app/src/main/java/net/rubygrapefruit/platform/test/Main.java

It seems that overflow arrives around 4000 events.
We currently generate 2^11 = 2048 directories, and deleting each produces 1 `REMOVED` and 0-2 `MODIFIED` events (depending on Windows' taste at the moment). The resulting number of events hovers around 4000 that seems to be some kind of limit.
By halving the size of the deleted hierarchy we can avoid the overflow.

Decrease folder depth to make sure we don't get an overflow on Windows

---

src/file-events/cpp/win_fsnotifier.cpp

We should not stop listening to a `WatchPoint` when an overflow event is received. Instead we should continue delivering the events after invalidating the whole watched hierarchy.
This is as it should be on Linux and macOS already, we only need to change the behavior on Windows.

Continue listening after overflow

---

src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/LinuxFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/OsxFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/WindowsFileEventFunctions.java
src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventFunctionsTest.groovy
test-app/src/main/java/net/rubygrapefruit/platform/test/Main.java

This allows us to add more configuration options without breaking backwards compatibility.

Use builder pattern to configure watcher

---

src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/headers/linux_fsnotifier.h
src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsOverflowTest.groovy

This removes the need to immediately process the `IN_IGNORED` events. We also remove the need for the `FINISHED` watch point state by removing any cancelled watchpoints immediately.

Keep track of recently cancelled watch points on Linux

---

src/file-events/cpp/apple_fsnotifier.cpp
src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/jni_support.cpp
src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/cpp/win_fsnotifier.cpp
src/file-events/headers/apple_fsnotifier.h
src/file-events/headers/generic_fsnotifier.h
src/file-events/headers/jni_support.h
src/file-events/headers/linux_fsnotifier.h
src/file-events/headers/win_fsnotifier.h
src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/LinuxFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/OsxFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/WindowsFileEventFunctions.java
src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
test-app/src/main/java/net/rubygrapefruit/platform/test/Main.java

Instead of starting and handling threads in C++, we now set up the thread in Java. This allows for a number of simplifications in the native code and gives us all the Java tools for handling concurrency.

Move thread handling to Java

---

src/file-events/cpp/apple_fsnotifier.cpp
src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/cpp/win_fsnotifier.cpp
src/file-events/headers/apple_fsnotifier.h
src/file-events/headers/linux_fsnotifier.h
src/file-events/headers/win_fsnotifier.h

Instedd of utilizing the destructor we now call `terminate()` directly. This way we can avoid calling virtual methods from destructors.

Simplify termination

---

src/file-events/cpp/apple_fsnotifier.cpp
src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/cpp/win_fsnotifier.cpp
src/file-events/headers/generic_fsnotifier.h

This is just so much better than the `#define`s we used to use.

Use a native enum for file event types

---

src/file-events/cpp/apple_fsnotifier.cpp
src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/headers/generic_fsnotifier.h

There is no advantage to having both `IS_SET` and `IS_ANY_SET` and the ambiguity makes this error-prone.

Use only IS_SET to test for flags

---

src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/jni_support.cpp
src/file-events/cpp/win_fsnotifier.cpp
src/file-events/headers/generic_fsnotifier.h
src/file-events/headers/jni_support.h
src/file-events/headers/win_fsnotifier.h
src/main/java/net/rubygrapefruit/platform/file/FileWatchEvent.java
src/main/java/net/rubygrapefruit/platform/file/FileWatcher.java
src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/LinuxFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/NativeLogger.java
src/main/java/net/rubygrapefruit/platform/internal/jni/OsxFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/WindowsFileEventFunctions.java
src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventFunctionsTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsOverflowTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/SymlinkFileEventFunctionsTest.groovy
test-app/src/main/java/net/rubygrapefruit/platform/test/Main.java

This has a number of benefits:
1) it simplifies the code somewhat as there is no need to handle exceptions in user code on the native side,
2) ~~it simplifies test code a lot, as we don't need to handle async events,~~ (this part has been extracted into #160)
3) since the native thread is now free of user code execution, it is impossible for user code to try and run a command from this thread, preventing hard-to-debug hangs.
4) we can detect overflows to the event queue and change them into an overflow event

Use a BlockingQueue to pass events to the Java side

---

src/file-events/cpp/generic_fsnotifier.cpp
src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy

We tried to call the `changeEvent` method instead of the `unknownEvent` method for unknown events. This caused JVM crashes.
The crash has been exposed by the unknown event caused by renaming the watched directory on Linux. I added a test for this.

Fix wrong method call for unknown events

---

src/file-events/cpp/apple_fsnotifier.cpp
src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/cpp/logging.cpp
src/file-events/cpp/win_fsnotifier.cpp
src/file-events/headers/generic_fsnotifier.h
src/file-events/headers/linux_fsnotifier.h
src/file-events/headers/logging.h
src/file-events/headers/win_fsnotifier.h

This is a C++11 feature that does not pollute the top-level scope.

Use an enum class to represent ChangeType

---

src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/headers/linux_fsnotifier.h

This is a sign that the watch point has been removed recently and we should treat it as a normal event and not fail.
Fixes https://github.com/gradle/native-platform/issues/195.

Do not fail if cancelling watch point returns EINVAL

---

build.gradle
src/file-events/cpp/apple_fsnotifier.cpp

Ignore all events that normalize to a 0 flag.
Fixes #209.

Normalize events on macOS

---

src/file-events/cpp/linux_fsnotifier.cpp

We are releasing the memory pointed to by path here, so it should happen only after the path is used in the log message.
Fixes #215.

Do not release memory for path too early

---

src/file-events/cpp/win_fsnotifier.cpp

[`CloseHandle()` can throw](https://docs.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-closehandle#return-value) a [structured exception (SEH)](https://docs.microsoft.com/en-us/cpp/cpp/structured-exception-handling-c-cpp?view=vs-2019) which we must handle in `WatchPoint::close()` instead of letting it bubble up to `~WatchPoint()`.

Handle exception thrown by CloseHandle Windows API

---

.teamcity/NativePlatformPublishing.kt

when publishing. So it is easier to find the published
DLLs, SOs, etc.
Fixes #224.

Archive everything in the libs directory

---

src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/cpp/services.cpp
src/file-events/headers/generic_fsnotifier.h
src/file-events/headers/linux_fsnotifier.h
src/main/java/net/rubygrapefruit/platform/file/FileWatcher.java
src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
src/main/java/net/rubygrapefruit/platform/internal/jni/InotifyInstanceLimitTooLowException.java
src/main/java/net/rubygrapefruit/platform/internal/jni/InotifyWatchesLimitTooLowException.java
src/main/java/net/rubygrapefruit/platform/internal/jni/InsufficientResourcesForWatchingException.java
src/main/java/net/rubygrapefruit/platform/internal/jni/LinuxFileEventFunctions.java

We now throw specialized exception when we reach the inotify limits on Linux. This can then be handled by clients of native platform to display helpful messages.

Throw specialized exceptions for Linux inotify limits

---

.teamcity/Agent.kt
.teamcity/Os.kt
.teamcity/extensions.kt

Now that the Linux agents set `agent.os.distribution.name`.

Simplify targetting the agents

---

.teamcity/NativePlatformBuild.kt
.teamcity/NativePlatformCompatibilityTest.kt
build.gradle

This PR configures a build on CentOS, so it uses the already built artifacts from the upstream builds to run the native platform test on CentOs 8. It replaces the artifacts built in the current build by the artifacts from an external repository via dependency substitution, so the native libraries are not rebuilt on CentOS.

Run compatibility tests on CentOs

---

src/file-events/cpp/apple_fsnotifier.cpp
src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/cpp/win_fsnotifier.cpp
src/file-events/headers/apple_fsnotifier.h
src/file-events/headers/generic_fsnotifier.h
src/file-events/headers/linux_fsnotifier.h
src/file-events/headers/win_fsnotifier.h
src/main/java/net/rubygrapefruit/platform/internal/jni/OsxFileEventFunctions.java
src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy
src/test/groovy/net/rubygrapefruit/platform/file/SymlinkFileEventFunctionsTest.groovy

Previously we started an event stream for each individual directory hierarchy we watched. This seems to be overly expensive and there's also a limit of ~1000 event streams per machine that we might hit. So instead we are now using a single event stream that watches multiple directory hierarchies.
This makes adding/removing watches slightly slower.
There's also a change in behavior wrt watching the same directory both directly and via a symlink: in this case changes are not reported twice with the same path anymore, which is arguably better.

Use a single FSEventStream

---

src/file-events/cpp/apple_fsnotifier.cpp
src/file-events/headers/apple_fsnotifier.h

Previously we updated event streams after the changes were made. This could cause race conditions when changes keep coming in for the unregistered events.

Close event stream before modifying watch point registrations

---

src/file-events/cpp/apple_fsnotifier.cpp
src/file-events/cpp/generic_fsnotifier.cpp
src/file-events/cpp/linux_fsnotifier.cpp
src/file-events/cpp/win_fsnotifier.cpp
src/file-events/headers/apple_fsnotifier.h
src/file-events/headers/generic_fsnotifier.h
src/file-events/headers/linux_fsnotifier.h
src/file-events/headers/win_fsnotifier.h
src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy

We've been using `mutex` in a bad way:
* on Windows we don't even need to guard `watchPoints` as all the mutation happens on the run loop thread anyway, so that's removed now,
* for macOS and Linux we should have been using `recursive_mutex` instead, as it allows reentry—this is also fixed now.
After #238 has been reverted in #248, we can still salvage a number of improvements that happened as part of the original PR. These are ported here, too.

Fix watch point mutation locking

---

file-events/src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java

If the timeout is 0, that means to wait forever, and if the timeout is < 0, then Thread.join() will throw an exception.
Fixes #259.

Only wait for the watcher thread to finish if there is some time remaining

---

native-platform/src/test/groovy/net/rubygrapefruit/platform/memory/MemoryTest.groovy

This is to work around https://github.com/gradle/native-platform/issues/262 for now.

Temporarily disable failing test

---

.teamcity/Agent.kt
.teamcity/Os.kt

So we can keep compatibility with Ubuntu 16 while upgrading our TC agent fleet to Ubuntu 20.

Use Ubuntu 16 images for building native platform

---

native-platform/src/main/cpp/win.cpp
native-platform/src/main/java/net/rubygrapefruit/platform/file/FileSystemInfo.java
native-platform/src/main/java/net/rubygrapefruit/platform/internal/DefaultFileSystemInfo.java
native-platform/src/main/java/net/rubygrapefruit/platform/internal/FileSystemList.java
native-platform/src/test/groovy/net/rubygrapefruit/platform/file/FileSystemsTest.groovy

We converted the C-String to a Java String before `GetVolumeInformationW` wrote it.

Fix bug for resolving file system type on Windows

---

file-events/src/file-events/cpp/linux_fsnotifier.cpp
gradle/wrapper/gradle-wrapper.properties

On Alpine Linux in a Docker container we've seen that it is possible that calling `inotify_rm_watch()` immediately produces the `IN_IGNORED` event, which in turn can result in the watch point to be deleted before returning from the `cancel()` method, resulting in a crash.
This change ensures that we ignore already removed watch points instead.

Ignore already removed watch points on Linux

---

file-events/src/file-events/cpp/linux_fsnotifier.cpp
file-events/src/main/java/net/rubygrapefruit/platform/internal/jni/LinuxFileEventFunctions.java

This is primarily targeted at musl libc that seems to have problems with watching files on Linux, causing crashes in Gradle. See https://github.com/gradle/gradle/issues/17099.

Disable file events on non-glibc implementations on Linux

---

file-events/src/file-events/cpp/win_fsnotifier.cpp
file-events/src/file-events/headers/win_fsnotifier.h
file-events/src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy

Use the new `ReadDirectoryChangesExW()` API (instead of the old `ReadDirectoryChangesW()`) introduced in Windows 10, version 1907 in 2017.
The new API is available on all Windows 10 versions currently supported by Microsoft except for two LTSC versions released in 2015 and 2016. The latest LTSC version released in 2018 is supported.
On unsupported versions of Windows the expected behavior is that the library will fail to load with a missing symbol, and thus we'll report that file events are unavailable.
The new API does not seem to emit as many random extra events (aka "optional events"), though this might be something that was also fixed in the old API in a recent Windows update. In any case, the PR removes most (but not all) `optionalChange()` expectations.

Use new ReadDirectoryChangesExW() API

---

native-platform/src/main/cpp/win.cpp

`GetFileInformationByHandleEx` returns ERROR_INVALID_PARAMETER
on FAT file systems, so this breaks stat.
See also https://go-review.googlesource.com/c/go/+/154377/.

Fix stat on Windows FAT file systems

---

file-events/src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy

It seems that when removing the whole watched hierarchy, the deleted files are not always reported as removed (only modified). This has been the case before we switched to `ReadDirectoryChangesExW()` in #287, so we are just reverting to testing the original behavior here.

Fix flaky test on Windows

---

file-events/src/file-events/cpp/jni_support.cpp
file-events/src/file-events/cpp/win_fsnotifier.cpp
file-events/src/file-events/headers/generic_fsnotifier.h
file-events/src/file-events/headers/jni_support.h
file-events/src/file-events/headers/win_fsnotifier.h
file-events/src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
file-events/src/main/java/net/rubygrapefruit/platform/internal/jni/LinuxFileEventFunctions.java
file-events/src/main/java/net/rubygrapefruit/platform/internal/jni/OsxFileEventFunctions.java
file-events/src/main/java/net/rubygrapefruit/platform/internal/jni/WindowsFileEventFunctions.java
file-events/src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventFunctionsTest.groovy
file-events/src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
file-events/src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy
file-events/src/test/groovy/net/rubygrapefruit/platform/file/SymlinkFileEventFunctionsTest.groovy

Windows handles file watching using relative paths. When the watched directory is moved, Windows sends no notification. A client keeping track of absolute paths faces two problems:
1) when changes are made to the contents of the moved directory, changes are still reported as if they happened under the original, registered root,
2) there is no way to know if the original location has completely disappeared due to a move.
(Note that if the original watched root is deleted, Windows does send a notification, so this is just about renames/moves.)
The problems are addressed in this PR as follows:
1) we are now reporting the moved locations for further changes,
2) while we still can't get notified about the original location being moved away, there is now a new API …

Handle watched directory moved on Windows

---

file-events/src/file-events/cpp/win_fsnotifier.cpp
file-events/src/file-events/headers/win_fsnotifier.h
file-events/src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy

There is a bug where we re-check already `FINISHED` watch points in `stopWatchingMovedPaths()`. We should also handle the case when `getPath()` fails for whatever reason.

Handle moved watched handles on Windows more resiliently

---

file-events/src/file-events/cpp/linux_fsnotifier.cpp
file-events/src/file-events/cpp/win_fsnotifier.cpp
file-events/src/file-events/headers/linux_fsnotifier.h
file-events/src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
file-events/src/main/java/net/rubygrapefruit/platform/internal/jni/LinuxFileEventFunctions.java
file-events/src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
file-events/src/test/groovy/net/rubygrapefruit/platform/file/MovedDirectoriesFileEventFunctionsTest.groovy
file-events/src/test/groovy/net/rubygrapefruit/platform/file/WindowsFileEventFunctionsTest.groovy

A variation on #299, which allows passing in a list of locations to check. This avoids checking all the watched paths, which may be quite expensive on Linux.

Allow checking for moved paths on Linux

---

file-events/src/file-events/cpp/linux_fsnotifier.cpp
file-events/src/file-events/headers/linux_fsnotifier.h
file-events/src/main/java/net/rubygrapefruit/platform/internal/jni/LinuxFileEventFunctions.java
file-events/src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
file-events/src/test/groovy/net/rubygrapefruit/platform/file/MovedDirectoriesFileEventFunctionsTest.groovy
file-events/src/test/groovy/net/rubygrapefruit/platform/file/WindowsFileEventFunctionsTest.groovy

When the parent of a watched directory is moved to a different location on Linux, the kernel does not report any event. This is a similar problem to what we had on Windows: https://github.com/gradle/native-platform/pull/290.
The solution is similar, too: add a `LinuxFileWatcher.stopWatchingMovedPaths()` method.

Expose functionality to stop watching moved paths on Linux

---

file-events/src/file-events/cpp/generic_fsnotifier.cpp
file-events/src/file-events/cpp/jni_support.cpp
file-events/src/file-events/cpp/linux_fsnotifier.cpp
file-events/src/file-events/headers/generic_fsnotifier.h
file-events/src/file-events/headers/jni_support.h
file-events/src/file-events/headers/linux_fsnotifier.h
file-events/src/test/groovy/net/rubygrapefruit/platform/file/MovedDirectoriesFileEventFunctionsTest.groovy

If a directory isn't watched any more on Linux, it should be reported by `stopWatchingMovedPaths()`, so the client can drop he state it retains for the unwatched directory as well.

Report unwatched directories as moved on stopWatchingMovedPaths

---

buildSrc/build.gradle
buildSrc/src/main/java/gradlebuild/JniNokeePlugin.java
buildSrc/src/main/java/gradlebuild/NcursesVersion.java
buildSrc/src/main/java/gradlebuild/WindowsDistribution.java
file-events/build.gradle
native-platform/build.gradle

Fixes https://github.com/gradle/native-platform/issues/297.
See the attached issues for general work items left to do. Feel free to provide any kind of feedback on this PR either by starting a new conversation or contributing to a current conversation.

Migrate from core native to Nokee plugins

---

.teamcity/NativePlatformBuild.kt
.teamcity/extensions.kt
buildSrc/src/main/java/gradlebuild/NativePlatformComponentPlugin.java
native-platform/src/test/groovy/net/rubygrapefruit/platform/file/FileSystemsTest.groovy

I added an xfs and a btrfs partition to the Ubuntu amd64 AMIs. We can now run the file event tests there as well to see that those two file systems are supported as well.

Test file events on xfs and btrfs

---

buildSrc/build.gradle
buildSrc/src/main/java/gradlebuild/BuildableExtension.java
buildSrc/src/main/java/gradlebuild/FreeBsdRuntimePlugin.java
buildSrc/src/main/java/gradlebuild/JavaNativeInterfaceLibraryProperties.java
buildSrc/src/main/java/gradlebuild/JavaNativeInterfaceLibraryUtils.java
buildSrc/src/main/java/gradlebuild/JniNokeePlugin.java
buildSrc/src/main/java/gradlebuild/NativeRulesUtils.java
buildSrc/src/main/java/gradlebuild/NcursesRuntimePlugin.java
buildSrc/src/main/java/gradlebuild/actions/MixInJavaNativeInterfaceLibraryProperties.java
buildSrc/src/main/java/gradlebuild/actions/RegisterJniTestTask.java
file-events/build.gradle
native-platform/build.gradle

This PR relies on a locally published Nokee distribution with two minor fixes: 1) predicate filter for build variant and 2) ignores dimension with empty names when computing names. The final solution for those fixes will soon be integrated into master.
This PR focus on migrating the support for FreeBSD, Ncurses, publications and testJni task. All build features haven't been tested yet which is the next step in the migration.

Completes the migration to Nokee plugins

---

file-events/src/file-events/cpp/generic_fsnotifier.cpp
file-events/src/file-events/headers/generic_fsnotifier.h
file-events/src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java

Publish `TerminateEvent` after any errors related to stopping the native processor thread have been reported to the queue. This prevents the thread processing the event queue from exiting before seeing the `FailureEvent`.
Fixes https://github.com/gradle/native-platform/issues/319.

Report run loop termination errors before reporting the termination itself

---

native-platform/src/main/cpp/win.cpp
native-platform/src/main/java/net/rubygrapefruit/platform/internal/DefaultWindowsMemory.java
native-platform/src/main/java/net/rubygrapefruit/platform/internal/DefaultWindowsMemoryInfo.java
native-platform/src/main/java/net/rubygrapefruit/platform/internal/Platform.java
native-platform/src/main/java/net/rubygrapefruit/platform/internal/jni/WindowsMemoryFunctions.java
native-platform/src/main/java/net/rubygrapefruit/platform/memory/WindowsMemory.java
native-platform/src/main/java/net/rubygrapefruit/platform/memory/WindowsMemoryInfo.java
native-platform/src/shared/headers/win.h
native-platform/src/test/groovy/net/rubygrapefruit/platform/memory/MemoryTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/memory/OsxMemoryTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/memory/WindowsMemoryTest.groovy
readme.md
test-app/src/main/java/net/rubygrapefruit/platform/test/Main.java

This uses the `GetPerformanceInfo` API to access the information.

Add support for memory commit information on Windows

---

.gitignore
.vscode/c_cpp_properties.json
buildSrc/src/main/java/gradlebuild/JniPlugin.java
file-events/build.gradle
file-events/src/file-events/cpp/apple_fsnotifier.cpp
file-events/src/file-events/cpp/generic_fsnotifier.cpp
file-events/src/file-events/cpp/jni_support.cpp
file-events/src/file-events/headers/apple_fsnotifier.h
file-events/src/file-events/headers/generic_fsnotifier.h
readme.md

The [FSEventStreamScheduleWithRunLoop](https://developer.apple.com/documentation/coreservices/1447824-fseventstreamschedulewithrunloop?language=objc) API we've been using has been deprecated since macOS 13. We need to switch to [FSEventStreamSetDispatchQueue](https://developer.apple.com/documentation/coreservices/1444164-fseventstreamsetdispatchqueue?language=objc).
Fixes #315.
This also bumps C++ from C++11 to C++17 on macOS to get access to `std::variant`.
That means we stop support for macOS 10.9 and require macOS 10.13.
According to https://endoflife.date/macos, macOS 10.12 Sierra (the latest we'll stop supporting) has received the last update (10.12.6) on 19 Jul 2017, more than 6.5 years ago, and has been in end-of-life since 1 Oct 2019, almost 4.5 years ago.
Even macOS 10.13 High …

Switch to using FSEventStreamSetDispatchQueue on macOS for file events

---

.teamcity/NativePlatformBuild.kt

So it won't wait for an agent it does not need

TeamCity: turn the test trigger job into a composite

---

native-platform/src/main/java/net/rubygrapefruit/platform/Native.java
native-platform/src/main/java/net/rubygrapefruit/platform/internal/NativeLibraryLocator.java
native-platform/src/test/groovy/net/rubygrapefruit/platform/NativePlatformSpec.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/ProcessLauncherTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/ProcessTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/SystemInfoTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/WindowsRegistryTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/file/AbstractFilesTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/file/FileSystemsTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/file/FilesTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/file/PosixFilesTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/file/WindowsFilesTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/internal/NativeTypeInfoTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/internal/PrompterTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/memory/MemoryTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/memory/OsxMemoryTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/memory/WindowsMemoryTest.groovy
native-platform/src/test/groovy/net/rubygrapefruit/platform/terminal/TerminalsTest.groovy
test-app/src/main/java/net/rubygrapefruit/platform/test/Main.java

Previously we'd implicitly initialize the native integration, causing binaries to be extracted in the system temp directory. This is a security vulnerability and thus is not allowed anymore. Instead we now throw if native integrations are queried without initialization.

Require explicit initialization of native integration
