- readme.md
Also fix unmappable character in README
> Switch URLs in README to HTTPS

- gradle/init-scripts/build-scan.init.gradle.kts
- settings.gradle
and add init script for configuring it.
> Apply build scan plugin

- test-app/src/main/java/net/rubygrapefruit/platform/test/Main.java
So we can easily try out watching a directory on macOs or Windows.
> Add --watch to test app

- .teamcity/NativePlatformBuild.kt
- .teamcity/NativePlatformPublishing.kt
- .teamcity/Os.kt
- .teamcity/extensions.kt
- .teamcity/settings.kts
> Publish commit status to Github

- build.gradle
This allows composite build to work when used together
with native platform
> Add native publication in current model

- build.gradle
> Apply test retry plugin

- build.gradle
- src/test/groovy/net/rubygrapefruit/platform/ProcessTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/memory/OsxMemoryTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/testfixture/JavaVersion.groovy
- src/test/groovy/net/rubygrapefruit/platform/testfixture/JavaVersionTest.groovy
This is to fix compiling tests using Java 9+.
> Upgrade to Spock 1.3

- .teamcity/Agent.kt
- .teamcity/extensions.kt
So we can add agents with different ncurses versions.
> Explicitly require ncurses version

- src/main/cpp/apple_fsnotifier.cpp
- src/main/java/net/rubygrapefruit/platform/file/FileWatcherCallback.java
- src/shared/headers/generic.h
- src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventsTest.groovy
We've missed a few up until now.
> Listen to all events on macOS

- src/main/cpp/win_fsnotifier.cpp
- src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventsTest.groovy
> Fix windows rename detection

- src/main/cpp/apple_fsnotifier.cpp
- src/main/cpp/win_fsnotifier.cpp
- src/main/java/net/rubygrapefruit/platform/internal/jni/OsxFileEventFunctions.java
- src/shared/cpp/generic.cpp
- src/shared/headers/generic.h
- src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventsTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/file/OsxFileEventFunctionsTest.groovy
Fixes when merged via `gradle/gradle`: https://github.com/gradle/gradle/issues/12219
> Exception handling for macOS

- src/file-events/cpp/file-events-version.cpp
- src/main/java/net/rubygrapefruit/platform/internal/Platform.java
- src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
- src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventsTest.groovy
and initialize logging accordingly.
Fixes #103.
> Check version for file event functions

- .vscode/c_cpp_properties.json
- src/file-events/cpp/apple_fsnotifier.cpp
- src/file-events/cpp/generic_fsnotifier.cpp
- src/file-events/cpp/linux_fsnotifier.cpp
- src/file-events/cpp/win_fsnotifier.cpp
- src/file-events/headers/generic_fsnotifier.h
- src/file-events/headers/linux_fsnotifier.h
- src/main/java/net/rubygrapefruit/platform/internal/Platform.java
- src/main/java/net/rubygrapefruit/platform/internal/jni/LinuxFileEventFunctions.java
- src/main/java/net/rubygrapefruit/platform/internal/jni/OsxFileEventFunctions.java
- src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventsTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/file/LinuxFileEventFunctionsTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/file/OsxFileEventFunctionsTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/file/WindowsFileEventFunctionsTest.groovy
> Implement native file watcher for Linux

- src/file-events/cpp/linux_fsnotifier.cpp
There is no need to do so as closing the inotify's file descriptor will do everything necessary.
> Do not cancel watch descriptors on shutdown

- src/file-events/cpp/apple_fsnotifier.cpp
- src/file-events/cpp/linux_fsnotifier.cpp
- src/file-events/cpp/win_fsnotifier.cpp
- src/file-events/headers/apple_fsnotifier.h
- src/file-events/headers/generic_fsnotifier.h
- src/file-events/headers/linux_fsnotifier.h
- src/file-events/headers/win_fsnotifier.h
- src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventFunctionsTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy
Make the tests simpler to comprehend.
> Simplify test callbacks

- src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventFunctionsTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/file/SymlinkFileEventFunctionsTest.groovy
Let's merge the tests from https://github.com/gradle/native-platform/pull/159.
> Use a BlockingQueue in tests to simplify

- src/file-events/cpp/apple_fsnotifier.cpp
Looks like the simpler shutdown wasn't the cause of macOS late events in #139. Let's keep the simplification.
> macOS: Simplify shutdown

- src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
Instead of only testing for events happening directly under the watched directory.
> Test events in subdirectories

- src/file-events/cpp/apple_fsnotifier.cpp
- src/file-events/cpp/generic_fsnotifier.cpp
- src/file-events/cpp/linux_fsnotifier.cpp
- src/file-events/cpp/win_fsnotifier.cpp
- src/file-events/headers/generic_fsnotifier.h
- src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
- src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy
These are the two commits that were missing from https://github.com/gradle/native-platform/pull/185.
> Reorganize reporter methods

- src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventFunctionsTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
This might be problematic on Linux where directories need to be re-registered.
> Test watching recreating watched directory

- src/main/cpp/posix.cpp
We should be able to be as fast as Java NIO when stating files.
> Improve Linux and macOS stat performance

- src/test/groovy/net/rubygrapefruit/platform/file/AbstractFileEventFunctionsTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/file/BasicFileEventFunctionsTest.groovy
Follow up on https://github.com/gradle/native-platform/pull/127.
> Follow up on review comments

- src/file-events/headers/logging.h
- src/main/java/net/rubygrapefruit/platform/internal/jni/NativeLogger.java
For some reason we didn't handle ALL and OFF. Now we do.
> Handle all log levels

- .teamcity/Agent.kt
- .teamcity/NativePlatformBuild.kt
- .teamcity/NativePlatformPublishing.kt
- .teamcity/Os.kt
- .teamcity/extensions.kt
- .teamcity/settings.kts
so it is easier to target CentOS 8 for a build.
> Model operating system in a better way

- src/test/groovy/net/rubygrapefruit/platform/file/SymlinkFileEventFunctionsTest.groovy
We already had a test when the watched directory itself is a symlink. The behavior seems to be:
- macOS reports changes on the canonical path
- Linux and Windows report the changes to the watched path, since both OSes report only relative paths as changes and we map those changes back via the path to the watched directory.
That means that when the project directory or the parent of the project directory is a symlink, then we won't detect any changes in it.
> Add test for watching dir when the parent dir is a symlink

- .teamcity/NativePlatformBuild.kt
- .teamcity/NativePlatformPublishing.kt
- build.gradle
- buildSrc/src/main/java/BasePublishPlugin.java
- buildSrc/src/main/java/PublishPlugin.java
- buildSrc/src/main/java/PublishToBintrayTask.java
- buildSrc/src/main/java/ReleasePlugin.java
- buildSrc/src/main/java/UpdatePackageMetadataTask.java
- buildSrc/src/main/java/UploadPlugin.java
- buildSrc/src/main/java/UploadTask.java
- buildSrc/src/main/java/VariantsExtension.java
- buildSrc/src/main/java/VersionDetails.java
So there is no manual intervention necessary to make artifacts visible to the public when publishing to Bintray.
> Automatically publish on Bintray

- src/file-events/cpp/apple_fsnotifier.cpp
- src/file-events/cpp/generic_fsnotifier.cpp
- src/file-events/cpp/linux_fsnotifier.cpp
- src/file-events/cpp/win_fsnotifier.cpp
- src/file-events/headers/apple_fsnotifier.h
- src/file-events/headers/generic_fsnotifier.h
- src/file-events/headers/linux_fsnotifier.h
- src/file-events/headers/win_fsnotifier.h
- src/main/java/net/rubygrapefruit/platform/internal/jni/OsxFileEventFunctions.java
- src/test/groovy/net/rubygrapefruit/platform/file/FileEventFunctionsStressTest.groovy
- src/test/groovy/net/rubygrapefruit/platform/file/SymlinkFileEventFunctionsTest.groovy
> Revert macOS single FSEventStream

- file-events/src/main/java/net/rubygrapefruit/platform/internal/jni/AbstractFileEventFunctions.java
> Report failure when watcher thread exits without being shutdown

- native-platform/src/main/cpp/apple.cpp
- native-platform/src/test/groovy/net/rubygrapefruit/platform/memory/MemoryTest.groovy
> Fix getMemoryInfo on macOS

- buildSrc/src/main/java/gradlebuild/NcursesPlugin.java
> Support building multiple ncurses variants

- file-events/src/file-events/cpp/generic_fsnotifier.cpp
- file-events/src/file-events/cpp/win_fsnotifier.cpp
- file-events/src/file-events/headers/command.h
- file-events/src/file-events/headers/exception.h
- file-events/src/file-events/headers/generic_fsnotifier.h
- gradle/wrapper/gradle-wrapper.properties
Save some of the good stuff from PR #279.
> Salvage PR #279

- buildSrc/src/main/java/gradlebuild/JniPlugin.java
- file-events/src/file-events/cpp/jni_support.cpp
Separate PR to fix issues blocking #327
> Fix errors with newer toolchain warnings
